### ISSUE TITLE
Nothing happens after clicking the Icon

### ISSUE THREAD

**Issue by UnclePsymon** [S73ph4n/joplin_make_all_links#1]
Hi - Nothing happens after I click the Icon in the toolbar, so no links are being created. But the note gets marked as recently edited. 
I am using the Snap version for Linux. Thank you!

**Comment by S73ph4n** [comment]
Hi. Indeed, it was broken !
I've pushed a fixed version (V1.0.1) of the plugin. Can you confirm that updating solves it ?

**Comment by UnclePsymon** [comment]
Thats great! Well, i have trouble building the plugin with npm right now. Can i already install the new version with the Joplin plugin browser? Because i can only find version 1.0.0 there.

**Comment by S73ph4n** [comment]
Try again. I've published a version 1.0.3 which solves another issue, you should see it now.

**Comment by UnclePsymon** [comment]
Found it, and it works! Thanks, that is very handy :)
