### ISSUE TITLE
Plugin only processes the first 100 notes

### ISSUE THREAD

**Issue by laurent22** [S73ph4n/joplin_make_all_links#2]
Just so you know this line means that only the first 100 notes:

https://github.com/S73ph4n/joplin_make_all_links/blob/5eb16e4aaa72ee62a54a5f2898fe0e19304e46db/src/index.ts#L11

To process all notes, you would need to implement pagination:

https://joplinapp.org/api/references/rest_api/#pagination

**Comment by S73ph4n** [comment]
Nice catch, thanks !
Should be fixed now.
